version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: UTC
    open-pull-requests-limit: 10
    labels: [dependencies, npm]
    ignore:
      - dependency-name: "@types/node"
        versions: [">=21"]
  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: UTC
    open-pull-requests-limit: 10
    labels: [dependencies, npm]
  - package-ecosystem: npm
    directory: /apps/api
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: UTC
    open-pull-requests-limit: 10
    labels: [dependencies, npm]
  - package-ecosystem: npm
    directory: /packages/database
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: UTC
    labels: [dependencies, npm]
  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: monthly
    labels: [dependencies, docker]
  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: monthly
    labels: [dependencies, docker]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:00"
      timezone: UTC
    labels: [dependencies, github-actions]