apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signara
  namespace: signara
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/proxy-body-size: "60m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/limit-rps: "20"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - app.signara.innotel.us
        - api.signara.innotel.us
        - auth.signara.innotel.us
      secretName: signara-tls
  rules:
    - host: app.signara.innotel.us
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: web
                port: { number: 80 }
    - host: api.signara.innotel.us
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api
                port: { number: 80 }
    - host: auth.signara.innotel.us
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik
                port: { number: 80 }
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: signara-docs
  namespace: signara
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - docs.signara.innotel.us
      secretName: signara-docs-tls
  rules:
    - host: docs.signara.innotel.us
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: docs
                port: { number: 80 }