apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: signara

resources:
  - namespace.yaml
  - configmap.yaml
  - secrets.example.yaml
  - pvc.yaml
  - deployment-web.yaml
  - deployment-api.yaml
  - statefulset-postgres.yaml
  - statefulset-redis.yaml
  - statefulset-minio.yaml
  - statefulset-meilisearch.yaml
  - deployment-authentik.yaml
  - services.yaml
  - deployment-docs.yaml
  - ingress.yaml
  - hpa.yaml
  - networkpolicy.yaml