apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: signara
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: signara
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: signara
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 250Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: meilisearch-data
  namespace: signara
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi